<!--  e heq sepse nuk e afishoj grafikun ketu
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    
      google.load('visualization', '1', {'packages':['motionchart']});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string','country');
		data.addColumn('number','viti');
		data.addColumn('number','value');
        <?php
        /**
		foreach (unserialize($this->data) as $vlerarows){
            $addRow[]=$vlerarows["country"];
            $addRow[]=(int)$vlerarows["viti"];
            $addRow[]=(double)$vlerarows["value"];
			$addRows[]=$addRow;
			unset($addRow);
		}
		$text=json_encode($addRows);
       **/ ?>
        data.addRows(<?//=$text?>);
        var chart = new google.visualization.MotionChart(document.getElementById('chart_div'));
        var options = {};
        options['state'] ='{"yAxisOption":"2","dimensions":{"iconDimensions":["dim0"]},"yZoomedDataMax":240,"orderedByX":false,"showTrails":false,"playDuration":15000,"time":"2009","yZoomedDataMin":-1,"xZoomedIn":false,"yZoomedIn":false,"sizeOption":"_UNISIZE","uniColorForNonSelected":false,"nonSelectedAlpha":0.4,"yLambda":1,"duration":{"multiplier":1,"timeUnit":"Y"},"xZoomedDataMin":504921600000,"iconType":"BUBBLE","orderedByY":false,"colorOption":"2","xZoomedDataMax":1230768000000,"iconKeySettings":[],"xLambda":1,"xAxisOption":"_TIME"}';
        options['width'] =670;
        chart.draw(data, options);
      }	    
</script>
-->
<!-- shfaq kodin ketu -->
<script >
  var indicator = <?=$this->indicator?>;
</script>
<script type="text/javascript">
<!--
	$("#codedata").html('<?=serialize($this->data)?>');
//-->
</script>
<div id="workspace">
    <h3><?=$this->metadata[0]?></h3>
<textarea width="620"  id="codedata" readonly="readonly"  style=" width:620px;font:12px Arial; color:#666;"><?=serialize($this->data)?></textarea>
</div>
<br />
<!-- fund kodi -->
<script >
   var indicator = <?=$this->indicator?>;
</script>

<!-- fillim butona -->
<?php
//ikona per download skedari excel per nje indikator te dhene
$xlsfile = '/var/www/vhosts/data.al/subdomains/open/httpdocs/semanticfiles/excel/'.$this->indicator.'.xls';
if (file_exists($xlsfile)) {
    echo '<img src="/browser/xls_icon.gif" width="24" height="32" id="xls_button" alt="View excel file">';
} 

//n3 file button
$n3file = '/var/www/vhosts/data.al/subdomains/open/httpdocs/semanticfiles/rdf/'.$this->indicator.'.n3';
if (file_exists($n3file)) {
    echo '<img src="/browser/RDF_icon_96.gif" width="24" height="32" id="n3_button" alt="View rdf file (N3 triples)">';
} 

//xml file button
$xmlfile = '/var/www/vhosts/data.al/subdomains/open/httpdocs/semanticfiles/xml/'.$this->indicator.'.xml';
if (file_exists($xmlfile)) {
    echo '<img src="/browser/xml_icon.png" width="28" height="32" id="xml_button" alt="View XML file">';
}

?>
<img src="/browser/text-csv.png" width="24" height="32" alt="View rdf file">
<img src="/browser/kchart.png" width="24" height="32" id="graph" alt="Generate graph">
<img src="/browser/spark-logo1.png" width="24" height="32" id ="sparktable"  alt="Generate spark table">
<!-- fund butona-->