<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
<!-- forma e komentit -->
<form action="/index/comm/" id="searchForm">
   <input name="title" value="Titulli: <?=$this->metadata[0]?>" cols="50" style="width: 70%;"/>
   <textarea name="comment" cols="55" style="width: 70%;height: 150px;">
	</textarea><br />
	<input name="burimi" value="Burimi <?=$this->metadata[1]?>" readonly="readonly" style="width: 70%;"/>
   	<input name="emri" value="Emri juaj" style="width: 70%;"/>
   <input type="submit" value="Shto Artikull" />
</form>
<!-- fund forma e komentit -->

<!-- the result of the search will be rendered inside this div -->
<div id="result"></div>

<script>
  /* attach a submit handler to the form */
  $("#searchForm").submit(function(event) {
    /* stop form from submitting normally */
    event.preventDefault();

    /* get some values from elements on the page: */
    var $form = $( this ),
        term = $form.find( 'input[name="comment"]' ).val(),
        url = $form.attr( 'action' );

    /* Send the data using post and put the results in a div */
    $.post( url, { s: term },
      function( data ) {

          $( "#result" ).empty().append( "Emaili u dergua" );
          $("#searchForm").hide();
      }
    );
  });
</script>