	<!-- footer-bottom starts -->		
	<div id="footer-bottom">
		<div class="bottom-left">
			<p>
			All rights reserved &copy; 2011 <strong>Open Data Albania</strong>&nbsp; &nbsp; &nbsp;
			<a href="http://www.shqiperia.com/" title="Shqiperia">ShqiperiaCom</a>

			</p>
		</div>	
		
		<div class="bottom-right">
			<p>		

				<a href="/" title="Knowledge Explorer @Open Data Albania">Home</a> |
				<a href="http://www.ais.al">Nje projekt nga AIS</a> | 
				<a href="http://feeds.feedburner.com/OpenDataAlbaniaFeed" title="RSS Feed">RSS Feed</a>								
			</p>
		</div>
	<!-- footer-bottom ends -->		
	</div>
